name: View Github Secrets

on:
  workflow_dispatch:

jobs:
  configure-iis:
    runs-on: self-hosted
    environment: Development  

    steps:
      - name: Showing Secrets
        shell: powershell
        env:
          DB_CONNECTION: ${{ secrets.DBCONNECTION }}        

        run: |
          Write-Host "$DB_CONNECTION"
